version: '3.7'

services:
  webhook:
    image: mihazs/git-docker:php
    volumes:
      - "./git-repo:/var/repo"
      - "./redeploy.sh:/var/scripts/redeploy.sh"
    ports:
      - "9000"
    environment:
    